// Generated by React Router

import "react-router"

declare module "react-router" {
  interface Register {
    pages: Pages
    routeFiles: RouteFiles
    routeModules: RouteModules
  }
}

type Pages = {
  "/": {
    params: {};
  };
  "/agent": {
    params: {};
  };
  "/agent/marca": {
    params: {};
  };
  "/agent/about": {
    params: {};
  };
  "/agent/redux": {
    params: {};
  };
  "/agent/ant": {
    params: {};
  };
  "/*": {
    params: {
      "*": string;
    };
  };
};

type RouteFiles = {
  "root.tsx": {
    id: "root";
    page: "/" | "/agent" | "/agent/marca" | "/agent/about" | "/agent/redux" | "/agent/ant" | "/*";
  };
  "../src/pages/loginPage/loginPage.tsx": {
    id: "../src/pages/loginPage/loginPage";
    page: "/";
  };
  "../src/pages/agentPage/agentPage.tsx": {
    id: "../src/pages/agentPage/agentPage";
    page: "/agent" | "/agent/marca" | "/agent/about" | "/agent/redux" | "/agent/ant";
  };
  "../src/pages/shopsPage/shopsPage.tsx": {
    id: "../src/pages/shopsPage/shopsPage";
    page: "/agent";
  };
  "../src/pages/marcaPage/marcaPage.tsx": {
    id: "../src/pages/marcaPage/marcaPage";
    page: "/agent/marca";
  };
  "../src/pages/aboutPage/aboutPage.tsx": {
    id: "../src/pages/aboutPage/aboutPage";
    page: "/agent/about";
  };
  "../src/pages/counterPage/counterPage.tsx": {
    id: "../src/pages/counterPage/counterPage";
    page: "/agent/redux";
  };
  "routes/fortesting.tsx": {
    id: "routes/fortesting";
    page: "/agent/ant";
  };
  "../src/pages/catchAllPage/catchAllPage.tsx": {
    id: "../src/pages/catchAllPage/catchAllPage";
    page: "/*";
  };
};

type RouteModules = {
  "root": typeof import("./app/root.tsx");
  "../src/pages/loginPage/loginPage": unknown;
  "../src/pages/agentPage/agentPage": unknown;
  "../src/pages/shopsPage/shopsPage": unknown;
  "../src/pages/marcaPage/marcaPage": unknown;
  "../src/pages/aboutPage/aboutPage": unknown;
  "../src/pages/counterPage/counterPage": unknown;
  "routes/fortesting": typeof import("./app/routes/fortesting.tsx");
  "../src/pages/catchAllPage/catchAllPage": unknown;
};