// Generated by React Router

import "react-router"

declare module "react-router" {
  interface Register {
    pages: Pages
    routeFiles: RouteFiles
    routeModules: RouteModules
  }
}

type Pages = {
  "/": {
    params: {};
  };
  "/about": {
    params: {};
  };
  "/marca": {
    params: {};
  };
  "/fortesting": {
    params: {};
  };
  "/loginPage": {
    params: {};
  };
  "/counterpage": {
    params: {};
  };
  "/*": {
    params: {
      "*": string;
    };
  };
};

type RouteFiles = {
  "root.tsx": {
    id: "root";
    page: "/" | "/about" | "/marca" | "/fortesting" | "/loginPage" | "/counterpage" | "/*";
  };
  "../pages/loginPage/loginPage.tsx": {
    id: "../pages/loginPage/loginPage";
    page: "/";
  };
  "../pages/aboutPage/aboutPage.tsx": {
    id: "../pages/aboutPage/aboutPage";
    page: "/about";
  };
  "../pages/marcaPage/marcaPage.tsx": {
    id: "../pages/marcaPage/marcaPage";
    page: "/marca";
  };
  "routes/fortesting.tsx": {
    id: "routes/fortesting";
    page: "/fortesting";
  };
  "routes/loginPage.tsx": {
    id: "routes/loginPage";
    page: "/loginPage";
  };
  "../pages/counterPage/counterPage.tsx": {
    id: "../pages/counterPage/counterPage";
    page: "/counterpage";
  };
  "../pages/catchAllPage/catchAllPage.tsx": {
    id: "../pages/catchAllPage/catchAllPage";
    page: "/*";
  };
};

type RouteModules = {
  "root": typeof import("./app/root.tsx");
  "../pages/loginPage/loginPage": unknown;
  "../pages/aboutPage/aboutPage": unknown;
  "../pages/marcaPage/marcaPage": unknown;
  "routes/fortesting": typeof import("./app/routes/fortesting.tsx");
  "routes/loginPage": typeof import("./app/routes/loginPage.tsx");
  "../pages/counterPage/counterPage": unknown;
  "../pages/catchAllPage/catchAllPage": unknown;
};